apiVersion: v1
kind: ConfigMap
metadata:
  name: my-dotnet-project-config
  namespace: namespace-workflow-1771162579886
  labels:
    app.kubernetes.io/name: my-dotnet-project
    kubernetes.azure.com/generator: devhub
data: