apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-dotnet-project
  labels:
    app.kubernetes.io/name: my-dotnet-project
    app.kubernetes.io/part-of: my-dotnet-project-project
    kubernetes.azure.com/generator: devhub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-dotnet-project
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80