apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: my-dotnet-project
  labels:
    app.kubernetes.io/name: my-dotnet-project
    app.kubernetes.io/part-of: my-dotnet-project-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: my-dotnet-project